### ISSUE TITLE
Docker Monitoring error handling

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout-plugins#201]
@composit,

Looking at some errors w/the new Docker Monitoring Plugin. I'm seeing this one:

<pre>
Excon::Errors::SocketError: 757: unexpected token at '404 page not found 
' (JSON::ParserError) 
/usr/local/share/gems/gems/scout-5.9.8/vendor/json_pure/lib/json/common.rb:155:in `parse' 
/usr/local/share/gems/gems/scout-5.9.8/vendor/json_pure/lib/json/common.rb:155:in `parse' 
Docker Monitor:80:in `parse_stats' 
Docker Monitor:31:in `block in streamer' 
</pre>

I'm guessing either (1) it's not running a version of docker that supports the stats api (2) the stats api isn't enabled. We should check/return a better error message for this.

**Comment by composit** [comment]
Added better error handling if API endpoint is unreachable: https://github.com/scoutapp/scout-plugins/commit/a7a2b2bc3347ae6cb8b33e479319c09f5963bebb
