### ISSUE TITLE
Versioning dependencies?

### ISSUE THREAD

**Issue by squarism** [scoutapp/scout-plugins#211]
`Gemfile` specifies `mysql2` but `Gemfile.lock` has `mysql` in it.  What is the purpose of the `Gemfile` in this project?  If someone wants to add a dependency to the plugins but the plugins are run on a private server, I see two options:

1. Manage the dependency yourself (write down the minimum version in the Readme?)
1. Use Gemfile.
  * Add the gem to `Gemfile`, `bundle update` and commit `Gemfile.lock`.
  * Clone this repo to a server as a part of deployment, run `bundle` to install the required gems.

Confused, I guess I'm missing something.

**Comment by itsderek23** [comment]
Chris,

The `Gemfile` is only for local plugin development - it's primarily used by our team.

Your two options are workable options for Gem dependencies.

**Comment by squarism** [comment]
The problem with doing this is stuff like this.  The `Gemfile` specifies mocha but mocha has changed.  Now the test suite doesn't work:

```
$ cd scout-plugins
$ bundle
$ cd {any plugin}
$ ruby test.rb
LoadError: cannot load such file -- mocha/test_unit
...
```

What you really mean is `gem install mocha -v (the version you installed last on your computer)` which is what `Gemfile.lock` solves.  Just trying to test a plugin before I submit but the test suite seems broken (to someone like me who is an outsider to "local plugin development").  Is that the intent?
