### ISSUE TITLE
Passenger plugin: capture app group queue

### ISSUE THREAD

**Issue by aharpervc** [scoutapp/scout-plugins#219]
Right now the passenger plugin only captures the global queue depth. However my understanding (at least for Passenger 4+) is that passenger will immediately hand requests to the app group and that the global queue depth will almost always be 0 even when there's no available workers to process requests. 

Therefore, in order to identify that you're having a problem, it's the "Requests in queue" for the group that's the important stat. Eg, the results of `passenger-status | grep -P '\s+Requests in queue: (\d+)'` where the output is 1 value per group.

I see that this could potentially be added here: https://github.com/scoutapp/scout-plugins/blob/master/passenger/passenger.rb#L40 but not sure how to also capture the name of the app group or to flow that through scout correctly.

**Comment by itsderek23** [comment]
@aharpervc - thanks for the report and what you are saying makes sense. 

We've got a bit of a backlog we are working thru on plugin updates. If you want to dig in, we're happy to answer any questions. Otherwise, we'll dig in later in October.

**Comment by aharpervc** [comment]
Any update on this?

**Comment by andre** [comment]
@aharpervc this dropped off our radar, sorry. We'll look at it this week.

**Comment by andre** [comment]
@aharpervc what we're thinking of doing here is reporting the sum of the queue sizes for each group. That's simpler (and less error prone, I believe) than trying to specify which group to report on.

**Comment by aharpervc** [comment]
The problem is that the global number is not helpful because it's always 0, even when there's queued requests for an app. You have to look at queued requests per app group.

**Comment by andre** [comment]
> The problem is that the global number is not helpful because it's always 0, even when there's queued requests for an app. You have to look at queued requests per app group.

Yep, that's what we're going to do -- we'll grab the queued requests per app group, sum them up, and report the result.

**Comment by aharpervc** [comment]
Oh, ok. Sounds good.

**Comment by numy1448** [comment]
@aharpervc the plugin has been updated and ready to apply. What is your account so that I can update it for you?

**Comment by aharpervc** [comment]
@numy1448 great! Not sure what you need from me, do you mean an account id or something? Is this something you can configure on your end or will I need to update scoutd or what?

**Comment by itsderek23** [comment]
@aharpervc - sorry for the confusion. Just click the "update code" button in the Scout UI for the latest. 

If you are having trouble, shoot an email to support@scoutapp.com along w/the URL on scoutapp.com of the plugin install.

**Comment by aharpervc** [comment]
Got it, thanks. Everything appears to be working, but now I need a traffic spike to get something to show up for that stat on a dashboard.

**Comment by itsderek23** [comment]
A dirty, shameless plugin: we recently added [time-in-queue instrumentation](http://blog.scoutapp.com/articles/2015/12/22/scout-apm-release-request-queuing-and-middleware-instrumentation) to Scout app monitoring.

The advantage of tracking time-in-queue vs. Passenger Queue Lengths: since this plugin runs once per-minute, it will miss spikes that exist outside that time. Time-in-queue on Scout APM is tracked on EVERY request.
